import React from "react"
import { RadioField, RadioGroup } from "./Radio"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=9762%3A1412",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
      description: figma.string("Description"),
      placeholder: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "hasDescription": figma.boolean('Has Description'),
      // "description": figma.string('Description'),
      // "label": figma.string('Label'),
      // "valueType": figma.enum('Value Type', {
      //   "Unchecked": "unchecked",
      //   "Checked": "checked"
      // })
    },
    example: (props) => (
      <RadioField
        value={/* TODO */}
        isDisabled={props.isDisabled}
        hidden={props.hidden}
        label={props.label}
        description={props.description}
        placeholder={props.placeholder}
      />
    ),
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=624%3A23642",
  {
    props: {},
    example: (props) => <RadioGroup />,
  },
)
