import React from "react";
import { SelectField } from "./Select";
import figma from "@figma/code-connect";

/**
 * Auto-generated by Code Connect, then cleaned to ensure valid mappings.
 */

figma.connect(
  SelectField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=2136%3A2336",
  {
    props: {
      label: figma.string("Label"),
      description: figma.string("Description"),

      isDisabled: figma.enum("State", {
        Default: false,
        Error: false,
        Disabled: true,
      }),

      hasError: figma.enum("State", {
        Default: false,
        Error: true,
        Disabled: false,
      }),

      error: figma.string("Error"),

      isOpen: figma.boolean("Open"),
      defaultOpen: figma.boolean("Open"),

      hidden: figma.enum("State", {
        Default: false,
        Error: false,
        Disabled: true,
      }),
    },

    example: (props) => (
      <SelectField
        label={props.label}
        description={props.description}
        isDisabled={props.isDisabled}
        hasError={props.hasError}
        error={props.error}
        isOpen={props.isOpen}
        defaultOpen={props.defaultOpen}
        hidden={props.hidden}
      />
    ),
  }
);
