import React from "react"
import { SelectField } from "./Select"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SelectField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=2136%3A2336",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Description"),
      isOpen: figma.boolean("Open"),
      defaultOpen: figma.boolean("Open"),
      placeholder: figma.string("Label"),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
      description: figma.string("Description"),
      // No matching props could be found for these Figma properties:
      // "hasLabel": figma.boolean('Has Label'),
      // "hasError": figma.boolean('Has Error'),
      // "label": figma.string('Label'),
      // "error": figma.string('Error'),
      // "open": figma.boolean('Open'),
      // "description": figma.string('Description'),
      // "hasDescription": figma.boolean('Has Description'),
      // "value": figma.string('Value'),
      // "valueType": figma.enum('Value Type', {
      //   "Default": "default",
      //   "Placeholder": "placeholder"
      // })
    },
    example: (props) => (
      <SelectField
        isDisabled={props.isDisabled}
        name={props.name}
        isOpen={props.isOpen}
        defaultOpen={props.defaultOpen}
        placeholder={props.placeholder}
        hidden={props.hidden}
        label={props.label}
        description={props.description}
      />
    ),
  },
)
