import React from "react"
import { InputField } from "./Input"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InputField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=2136%3A2263",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      description: figma.string("Description"),
      placeholder: figma.string("Label"),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      value: figma.string("Value"),
      defaultValue: figma.string("Value"),
      name: figma.string("Description"),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "hasLabel": figma.boolean('Has Label'),
      // "hasError": figma.boolean('Has Error'),
      // "label": figma.string('Label'),
      // "error": figma.string('Error'),
      // "hasDescription": figma.boolean('Has Description'),
      // "description": figma.string('Description'),
      // "value": figma.string('Value'),
      // "valueType": figma.enum('Value Type', {
      //   "Default": "default",
      //   "Placeholder": "placeholder"
      // })
    },
    example: (props) => (
      <InputField
        label={props.label}
        description={props.description}
        placeholder={props.placeholder}
        isDisabled={props.isDisabled}
        value={props.value}
        defaultValue={props.defaultValue}
        name={props.name}
        hidden={props.hidden}
      />
    ),
  },
)
