import React from "react"
import { Tab } from "./Tab"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tab,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=3729%3A12963",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      rel: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover"
      // }),
      // "active": figma.boolean('Active')
    },
    example: (props) => <Tab rel={props.rel} />,
  },
)
