import React from "react"
import { SliderField } from "./Slider"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SliderField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=589%3A17676",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Description"),
      label: figma.string("Label"),
      description: figma.string("Description"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "description": figma.string('Description'),
      // "hasLabel": figma.boolean('Has Label'),
      // "hasDescription": figma.boolean('Has Description')
    },
    example: (props) => (
      <SliderField
        isDisabled={props.isDisabled}
        hidden={props.hidden}
        name={props.name}
        label={props.label}
        description={props.description}
      />
    ),
  },
)
