import React from "react"
import { Tag } from "./Tag"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tag,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=56%3A8830",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      scheme: figma.enum("Scheme", {
        Brand: "brand",
        Danger: "danger",
        Positive: "positive",
        Warning: "warning",
        Neutral: "neutral",
      }),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Secondary: "secondary",
      }),
      // No matching props could be found for these Figma properties:
      // "removable": figma.boolean('Removable'),
      // "label": figma.string('Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover"
      // })
    },
    example: (props) => <Tag scheme={props.scheme} variant={props.variant} />,
  },
)
