import React from "react"
import { CheckboxField, CheckboxGroup } from "./Checkbox"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=9762%3A1441",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isIndeterminate: figma.enum("Value Type", {
        Indeterminate: true,
      }),
      defaultSelected: figma.enum("State", {
        Default: true,
      }),
      isSelected: figma.enum("Value Type", {
        Checked: true,
      }),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Description"),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
      description: figma.string("Description"),
      placeholder: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "hasDescription": figma.boolean('Has Description'),
      // "description": figma.string('Description'),
      // "label": figma.string('Label')
    },
    example: (props) => (
      <CheckboxField
        isIndeterminate={props.isIndeterminate}
        defaultSelected={props.defaultSelected}
        isSelected={props.isSelected}
        isDisabled={props.isDisabled}
        name={props.name}
        hidden={props.hidden}
        label={props.label}
        description={props.description}
        placeholder={props.placeholder}
      />
    ),
  },
)

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxGroup,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=9762%3A1426",
  {
    props: {},
    example: (props) => <CheckboxGroup />,
  },
)
