import React from "react"
import { SwitchField } from "./Switch"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SwitchField,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=9762%3A1902",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      defaultSelected: figma.enum("State", {
        Default: true,
      }),
      isSelected: figma.enum("Value Type", {
        Checked: true,
      }),
      isDisabled: figma.enum("State", {
        Disabled: true,
      }),
      name: figma.string("Description"),
      hidden: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
      description: figma.string("Description"),
      placeholder: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "description": figma.string('Description'),
      // "hasLabel": figma.boolean('Has Label'),
      // "label": figma.string('Label'),
      // "hasDescription": figma.boolean('Has Description')
    },
    example: (props) => (
      <SwitchField
        defaultSelected={props.defaultSelected}
        isSelected={props.isSelected}
        isDisabled={props.isDisabled}
        name={props.name}
        hidden={props.hidden}
        label={props.label}
        description={props.description}
        placeholder={props.placeholder}
      />
    ),
  },
)
