import React from "react"
import { Navigation } from "./Navigation"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Navigation,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=515%3A5459",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      direction: figma.enum("Direction", {
        Column: "column",
        Row: "row",
      }),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "icon": figma.instance('Icon'),
      // "hasIcon": figma.boolean('Has Icon'),
      // "hasLabel": figma.boolean('Has Label'),
      // "state": figma.enum('State', {
      //   "Default": "default",
      //   "Hover": "hover",
      //   "Active": "active"
      // }),
      // "type": figma.enum('Type', {
      //   "Small": "small",
      //   "Medium": "medium"
      // })
    },
    example: (props) => <Navigation direction={props.direction} />,
  },
)
