import React from "react"
import { Button } from "./Button"
import figma from "@thredup/sds"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=4185%3A3778",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDisabled: figma.enum("State", {
        Default: false,
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      label: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "label": figma.string('Label'),
      // "iconEnd": figma.instance('Icon End'),
      // "hasIconEnd": figma.boolean('Has Icon End'),
      // "hasIconStart": figma.boolean('Has Icon Start'),
      // "iconStart": figma.instance('Icon Start')
    },
    example: (props) => (
      <Button
        isDisabled={props.isDisabled}
        size={props.size}
        variant={props.variant}
      >
      {props.label}
      </Button>
    ),
  },
)
