import React from "react"
import { Tooltip } from "./Tooltip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Tooltip,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=315%3A32700",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      placement: figma.enum("Placement", {
        Bottom: "end bottom",
        Top: "top",
        Left: "left",
        Right: "right",
      }),
      // No matching props could be found for these Figma properties:
      // "title": figma.string('Title'),
      // "body": figma.string('Body'),
      // "hasBody": figma.boolean('Has Body')
    },
    example: (props) => <Tooltip placement={props.placement} />,
  },
)
