import React from "react"
import { Search } from "./Search"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Search,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=2236%3A14989",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      readOnly: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "value": figma.string('Value'),
      // "valueType": figma.enum('Value Type', {
      //   "Filled": "filled",
      //   "Placeholder": "placeholder"
      // })
    },
    example: (props) => (
      <Search disabled={props.disabled} readOnly={props.readOnly} />
    ),
  },
)
