import React from "react"
import { Notification } from "./Notification"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Notification,
  "https://www.figma.com/design/LHY012YNsXScv2iTu5qaoz/Simple-Design-System?node-id=124%3A8256",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      isDismissible: figma.boolean("Dismissible"),
      icon: figma.instance("Icon"),
      variant: figma.enum("Variant", {
        Message: "message",
        Alert: "alert",
      }),
      // No matching props could be found for these Figma properties:
      // "dismissible": figma.boolean('Dismissible'),
      // "icon": figma.instance('Icon'),
      // "hasIcon": figma.boolean('Has Icon'),
      // "hasButton": figma.boolean('Has Button'),
      // "title": figma.string('Title'),
      // "body": figma.string('Body')
    },
    example: (props) => (
      <Notification
        isDismissible={props.isDismissible}
        icon={props.icon}
        variant={props.variant}
      />
    ),
  },
)
